-- AlterTable
ALTER TABLE "SiteWorkingHour"
ADD COLUMN "startDay" VARCHAR(16) NOT NULL DEFAULT 'SATURDAY',
ADD COLUMN "endDay" VARCHAR(16) NOT NULL DEFAULT 'SATURDAY',
ADD COLUMN "startTime" VARCHAR(5) NOT NULL DEFAULT '08:00',
ADD COLUMN "endTime" VARCHAR(5) NOT NULL DEFAULT '20:00';
